name: Build and test of Java Project
 
on: [push]
 
jobs:
 build:
   runs-on: ubuntu-latest
   timeout-minutes: 2.5
   services:
            mysql:
                image: mysql:5.7
                env:
                   MYSQL_ALLOW_EMPTY_PASSWORD: yes
                   MYSQL_ROOT_PASSWORD: root
                   MYSQL_DATABASE: inmobiliaria
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     - name: Setup timezone
       uses: zcong1993/setup-timezone@master
       with:
          timezone: Europe/Madrid
     - name: Create test database
       run: |
         sudo /etc/init.d/mysql start
         mysql -u root -proot -e "SELECT VERSION();SELECT NOW();SELECT LOCALTIME() FROM DUAL"
         mysql -u root -proot  < ./create_tables.sql
         mysql -u root -proot -e "use inmobiliaria;Show tables"
     - name: Build with Maven
       run: mvn -B test --file pom.xml

